services:
  # TFTP-only server
  server:
    container_name: tftp-server
    image: kaczmar2/tftp-server:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-UTC}
      - ENABLE_WEBSERVER=false
      # - TFTP_ARGS=${TFTP_ARGS:-}  # Optional: Override default TFTP arguments (uncomment to customize)
    volumes:
      - ${TFTP_ROOT:-/srv/docker/tftp}:/srv/tftp
      - /etc/localtime:/etc/localtime:ro
    profiles:
      - server-only

  # TFTP + BusyBox httpd web server
  server-web:
    container_name: tftp-web-server
    image: kaczmar2/tftp-server:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-UTC}
      - ENABLE_WEBSERVER=true
      # - TFTP_ARGS=${TFTP_ARGS:-}  # Optional: Override default TFTP arguments (uncomment to customize)
    volumes:
      - ${TFTP_ROOT:-/srv/docker/tftp}:/srv/tftp
      - ${WEB_ROOT:-/srv/docker/www}:/var/www
      - /etc/localtime:/etc/localtime:ro
    profiles:
      - server-web
      - default
