services:
  # TFTP-only server
  tftp-only:
    container_name: tftp-server
    image: ghcr.io/kaczmar2/tftp-server
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-UTC}
      - ENABLE_WEBSERVER=false
      # - TFTP_ARGS=${TFTP_ARGS:-}  # Optional: Override default TFTP arguments (uncomment to customize)
    volumes:
      - ${TFTP_ROOT:-/srv/docker/tftp}:/srv/tftp
    profiles:
      - tftp-only

  # TFTP + mini_httpd web server (default)
  tftp-web:
    container_name: tftp-server
    image: ghcr.io/kaczmar2/tftp-server
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-UTC}
      - ENABLE_WEBSERVER=true
      - WEB_PORT=${WEB_PORT:-80}
      # - TFTP_ARGS=${TFTP_ARGS:-}  # Optional: Override default TFTP arguments (uncomment to customize)
    volumes:
      - ${TFTP_ROOT:-/srv/docker/tftp}:/srv/tftp
      - ${WEB_ROOT:-/srv/docker/www}:/srv/www
